#!/bin/sh

function usage() {
   echo "USAGE: reload-term dark|light"
   exit 1
}

CFGDIR=~/.config/xresources

if [[ $# -ne 1 ]]; then
   usage
fi

if [[ $1 != 'dark' && $1 != 'light' ]]; then
   usage
fi

xrdb -merge $CFGDIR/solarized-$1
notify-send 'Repainted term'
