set nocompatible
"filetype off

set rtp+=~projedi/.config/vim/plugins/vundle
call vundle#rc()

let g:vundle_default_git_proto = 'git'

Bundle 'gmarik/vundle'

Bundle 'FuzzyFinder'
Bundle 'L9'
Bundle 'YankRing.vim'
Bundle 'LaTeX-Box-Team/LaTeX-Box'
Bundle 'spolu/dwm.vim'
Bundle 'sjl/gundo.vim'
Bundle 'nanotech/jellybeans.vim'
Bundle 'bitc/lushtags'
Bundle 'ujihisa/neco-ghc'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/nerdtree'
Bundle 'artoj/qmake-syntax-vim'
Bundle 'godlygeek/tabular'
Bundle 'majutsushi/tagbar'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'tpope/vim-fugitive'
Bundle 'szw/vim-smartclose.git'
Bundle 'terryma/vim-multiple-cursors'
Bundle 'Shougo/neocomplcache'
Bundle 'Shougo/neosnippet'
Bundle 'Rip-Rip/clang_complete'
Bundle 'haskell/haskell-mode-vim'
" Something is broken with it right now
"Bundle 'honza/vim-snippets'
Bundle 'nelstrom/vim-visual-star-search'
Bundle 'tpope/vim-unimpaired'
Bundle 'tpope/vim-repeat'

filetype plugin indent on

if has('gui_running')
   set guioptions="a"
   set mouse-=a
   set guifont=AnonymousPro\ 9
   map <C-S-V> "*p
endif

syntax on
colorscheme jellybeans

set encoding=utf-8
set wildignore+=*.so,*.class,*.hi,*.o
set relativenumber
set hlsearch
set incsearch
set backspace=indent,eol,start
set autoindent
set tabstop=3
set shiftwidth=3
set expandtab
set foldmethod=syntax
set laststatus=2
set statusline=\[%{fugitive#head(7)}\]\ %<%f\ %h%m%r%=%L,%c
set lazyredraw
set completeopt=menu,menuone,longest
set pumheight=30
set list
set listchars=tab:▸\ ,eol:¬

if has("cscope")
   set csto=0
   set cst
   set nocsverb
   " add any database in current directory
   if filereadable("cscope.out")
       cs add cscope.out
   " else add database pointed to by environment
   elseif $CSCOPE_DB != ""
       cs add $CSCOPE_DB
   endif
   set csverb
   set cscopetag
endif

nnoremap <F8> :noh<CR>
nnoremap <silent> <F3> :YRShow<CR>
nnoremap <silent> <F4> :GundoToggle<CR>
nnoremap <silent> <F10> :TagbarToggle<CR>
nnoremap <silent> <F11> :NERDTreeToggle<CR>
cnoremap w!! w !sudo tee >/dev/null %
" Snippet-ish: inserts current filename
inoremap \fn <C-R>=expand("%:t:r")<CR>
let g:yankring_replace_n_pkey = ''
let g:yankring_replace_n_nkey = ''
" This is now used in multiple cursors plugin
nnoremap <C-P> :FufBuffer<CR>
imap <C-k> <Esc>
vmap <C-k> <Esc>
cmap <C-k> <Esc>
vnoremap / <Esc>`</\%V
vnoremap ? <Esc>`>?\%V
"imap <expr><TAB> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : pumvisible() ? "\<C-n>" : "\<TAB>"
"smap <expr><TAB> neosnippet#expandable_or_jumpable() ?  "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
         \"\<Plug>(neosnippet_expand_or_jump)" :
         \ pumvisible() ? neocomplcache#close_popup() : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
         \"\<Plug>(neosnippet_expand_or_jump)" :
         \ pumvisible() ? neocomplcache#close_popup() : "\<TAB>"

call matchadd('ErrorMsg', '\s\+$')
call matchadd('ErrorMsg', '\%>80v.\+')

au FocusLost * set number
au FocusGained * set relativenumber
au InsertEnter * set number
au InsertLeave * set relativenumber

au BufEnter *.hsc setlocal filetype=haskell
au BufEnter *.pro setlocal filetype=qmake

au FileType haskell set omnifunc=necoghc#omnifunc

au FileType tex set indentexpr=

" Don't screw up folds when inserting text that might affect them, until
" leaving insert mode. Foldmethod is local to the window. Protect against
" screwing up folding when switching between windows.
"au InsertEnter * if !exists('w:last_fdm') | let w:last_fdm=&foldmethod | setlocal foldmethod=manual | endif
"au InsertLeave,WinLeave * if exists('w:last_fdm') | let &l:foldmethod=w:last_fdm | unlet w:last_fdm | endif

let mapleader = ';'
let g:tex_flavor = "latex"

let g:yankring_history_file = '.cache/yankring_history'

let g:fuf_dataDir = '~/.cache/vim-fuf-data'

let g:LatexBox_Folding = 1
let g:LatexBox_fold_envs = 1

let NERD_haskell_alt_style=0

let g:smartclose_default_mapping_key = '<F7>'

"let g:multi_cursor_use_default_mapping = 0
let g:multi_cursor_next_key = '<A-n>'
let g:multi_cursor_prev_key = '<A-p>'
let g:multi_cursor_skip_key = '<C-x>'
let g:multi_cursor_quit_key = '<C-k>'

let g:necoghc_enable_detailed_browse = 1

let NERDTreeIgnore=['.swp$', '.hi$', '.o$']

let g:neocomplcache_enable_at_startup = 1
let g:neocomplcache_temporary_dir = '/tmp/neocomplcache'
let g:neocomplcache_enable_auto_select = 0

" C/C++ autocompletion
if !exists('g:neocomplcache_force_omni_patterns')
  let g:neocomplcache_force_omni_patterns = {}
endif
let g:neocomplcache_force_overwrite_completefunc = 1
let g:neocomplcache_force_omni_patterns.c =
      \ '[^.[:digit:] *\t]\%(\.\|->\)'
let g:neocomplcache_force_omni_patterns.cpp =
      \ '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::'
let g:neocomplcache_force_omni_patterns.objc =
      \ '[^.[:digit:] *\t]\%(\.\|->\)'
let g:neocomplcache_force_omni_patterns.objcpp =
      \ '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::'
let g:clang_complete_auto = 0
let g:clang_auto_select = 0

let hs_highlight_types = 1
let hs_highlight_more_types = 1
let hs_highlight_classes = 1
let hs_highlight_functions = 1
let hs_highlight_prelude = 1
