#source /etc/zsh/zprofile

export LANG="en_US.utf8"
export BROWSER=firefox
export EDITOR="/usr/bin/vim -u ~/.config/vim/vimrc -i ~/.cache/viminfo"
PATH=~projedi/.bin:$PATH
PATH=~projedi/.cabal/bin:$PATH
export PATH
export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
export C_INCLUDE_PATH=/usr/lib/jvm/java-6-openjdk/include
export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
export LESSHISTFILE=~projedi/.cache/lesshst
export VIMPERATOR_INIT=':source ~/.config/vimperator/vimperatorrc'
export VIMPERATOR_RUNTIME='~/.config/vimperator/data'
export RXVT_SOCKET=/tmp/urxvtd-socket
export IDEA_PROPERTIES=~/.config/idea.properties
export STUDIO_PROPERTIES=~/.config/android-studio.properties
export TEXMFVAR=~/.local/share/texmf-var
export ANDROID_SDK_HOME=~/.local/share/android-sdk
export TASKRC=~/.config/task/taskrc
export WINEPREFIX=/usr/local/games/Wine
export GST_REGISTRY=~/.local/share/gstreamer-registry.xml
export GIMP2_DIRECTORY=~/.config/gimp
#export PAGER=/usr/bin/less
#export MANPAGER=$PAGER
#export JACK_START_SERVER=1

eval `dircolors ~projedi/.config/dircolors`

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec /usr/lib/systemd/systemd --user
