#emulate sh -c 'source /etc/profile'
PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
export PATH
unset TERMCAP
unset MANPATH

if [[ "$(tty)" == /dev/tty* ]]; then
    [[ -n "$CDM_SPAWN" ]] && return
    [[ -z "$DISPLAY$SSH_TTY" ]] && exec cdm
fi
